/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.awt.DesktopBrowse;
import sun.net.util.URLUtil;
import static view.view_transaksi.openWebpage;

/**
 *
 * @author USER
 */
public class view_report extends javax.swing.JFrame {

    /**
     * Creates new form view_report
     */
    public view_report() {
        initComponents();
    }
    public static void openWebpage(String url){
        try {
            Desktop.getDesktop().browse(new URL(url).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        lapor_kasir = new javax.swing.JButton();
        lapor_terjual = new javax.swing.JButton();
        lapor_laris = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 49, 63));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 49, 63));
        jLabel2.setText("LAPORAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_add.setBackground(new java.awt.Color(204, 0, 0));
        btn_add.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Back");
        btn_add.setBorder(null);
        btn_add.setBorderPainted(false);
        btn_add.setContentAreaFilled(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setIconTextGap(2);
        btn_add.setOpaque(true);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        lapor_kasir.setBackground(new java.awt.Color(255, 255, 255));
        lapor_kasir.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        lapor_kasir.setText("Laporan Data Kasir");
        lapor_kasir.setBorder(null);
        lapor_kasir.setBorderPainted(false);
        lapor_kasir.setContentAreaFilled(false);
        lapor_kasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapor_kasir.setIconTextGap(2);
        lapor_kasir.setOpaque(true);
        lapor_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapor_kasirActionPerformed(evt);
            }
        });

        lapor_terjual.setBackground(new java.awt.Color(255, 255, 255));
        lapor_terjual.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        lapor_terjual.setText("Laporan Barang Terjual");
        lapor_terjual.setBorder(null);
        lapor_terjual.setBorderPainted(false);
        lapor_terjual.setContentAreaFilled(false);
        lapor_terjual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapor_terjual.setIconTextGap(2);
        lapor_terjual.setOpaque(true);
        lapor_terjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapor_terjualActionPerformed(evt);
            }
        });

        lapor_laris.setBackground(new java.awt.Color(255, 255, 255));
        lapor_laris.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        lapor_laris.setText("Laporan Barang Laris");
        lapor_laris.setBorder(null);
        lapor_laris.setBorderPainted(false);
        lapor_laris.setContentAreaFilled(false);
        lapor_laris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapor_laris.setIconTextGap(2);
        lapor_laris.setOpaque(true);
        lapor_laris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapor_larisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lapor_terjual, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lapor_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lapor_laris, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lapor_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lapor_laris, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lapor_terjual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        view_hompage vh = new view_hompage();
        vh.show();
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void lapor_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapor_kasirActionPerformed
        // TODO add your handling code here:
        try {
            openWebpage("http://localhost/java/laporan_kasir.php");
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lapor_kasirActionPerformed

    private void lapor_terjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapor_terjualActionPerformed
        // TODO add your handling code here:
        try {
            openWebpage("http://localhost/java/laporan_terjual.php");
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lapor_terjualActionPerformed

    private void lapor_larisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapor_larisActionPerformed
        // TODO add your handling code here:
        try {
            openWebpage("http://localhost/java/laporan_laris.php");
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lapor_larisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lapor_kasir;
    private javax.swing.JButton lapor_laris;
    private javax.swing.JButton lapor_terjual;
    // End of variables declaration//GEN-END:variables
}
